### ISSUE TITLE
Installation does not boot.

### ISSUE THREAD

**Issue by ozalboher** [dikamsiyoung/Lenovo-Yoga-720-15IKB-EFI-OpenCore-0.7.9#1]
hey , sorry to be a total noob here but I just can't get the installer to boot. What am I missing ?

*I downloaded Monterey from python.
*I downloaded the EFI folder you provided, I have the exact same computer so do I still need to modify something or just drag & drop to the USB stick?
* Do I still need to configure the SMBIOS ? Isn't it already configured in the EFI folder you've included? (And I don't have access to a MAC). 
* So any more steps that I am missing? (I just dragged and dropped the EFI folder to the USB stick).
* I am sure I configured the BIOS the correct way I even disabled CFG_LOCK in the advanced settings. 

I have the DEFAULT hardware that shipped with my laptop. (Lenovo Yoga 720 15-IKB).
much appreciated!!!

**Comment by dikamsiyoung** [comment]
Hi Ozalboher,

Yes it is very important to update your SMBIOS. I removed the SMBIOS in there. 

You can setup a macOS VMWare installation on your Windows partition and follow the Mac OpenCore USB creation guide.

Then follow the macOS in

**Comment by dikamsiyoung** [comment]
Also be aware that the stock SSD is the dreaded Samsung PM961 I mentioned at the end of the guide. 

It would boot but has never completed an installation on my build. Had to switch to WD SN750 Black

**Comment by dikamsiyoung** [comment]
I'd strongly suggest you go through the entire OpenCore guide especially
being that you are new to Hackintoshing. Even if you don't install it right
away, just having an understanding of how things work initially would save
you months I spent putting this up.

As for your questions:
1. You can choose any OpenCore version. Just make sure you update the files
required in the OpenCore update guide. I'm still testing latest OpenCore.

2. MacBook Pro 14.1 is the only one that gives you access to HDMI while
being able to sleep. 14.2 and 14.3 can sleep but don't have HDMi. Higher
SMBIOS don't sleep.

3. Since you are on stock hardware, no need to install kexts or change
order before installing.

4. Try to get the installation complete before attending to POST
Installations. There are some assumptions that you may have already
experienced some things before you get to the POST Installation phase.

As for VMWare, try searching how to install macOS on Windows using VMWare.
You don't need to partition.

The OpenCore guide details installation via Windows. I purposely left that
out of this guide.

**Comment by ozalboher** [comment]
thanks for the detailed comment !
I managed to boot to Monterey installation, but now it demands internet connection to install !
How would I connect to the internet ? there is no wi-fi option available , and I obviously the yoga 720 doesn't have the ethernet port.

**Comment by ozalboher** [comment]
I have the default wifi card. so that means I need to : 
 " Monterey
Ensure that IntelBluetoothInjector.kext or BrcmBluetoothInjector.kext is replaced with BluetoolFixup.kext. This comes with [BrcmPatchRAM](https://github.com/acidanthera/BrcmPatchRAM/releases). Also, make sure all kexts are updated then set MinKernel to 21.00.0 and MaxKernel to 20.99.9 in order to prevent Big Sur kexts from loading into Monterey. It also prevents Monterey kexts from loading into Big sur. "

 Didn't quite understand how in the lord's name I should install this.
I downloaded the " BrcmPatchRAM 2.6.1 DEBUG " from the website, now what? where are those kext that I need? i can't find them. And how do I install them? 

Please helppp i'm very close to finish this process....

**Comment by dikamsiyoung** [comment]
Very close indeed.

Do you have  Airport Itwlm kext present?

**Comment by dikamsiyoung** [comment]
WiFi should work out of the box as all kexts are installed.

That section is for Bluetooth as Apple changed a lot of things with
Monterey.

**Comment by dikamsiyoung** [comment]
Glad to hear it!

**Comment by ozalboher** [comment]
ok i booted successfully to the OS , but wifi and trackpad are not working.
any ideas?

**Comment by dikamsiyoung** [comment]
I have updated the branch to OpenCore 0.7.9
Try this new version

**Comment by ozalboher** [comment]
Hey,
My wi-fi works I replaced it with an intel chip. and trackpad is working too.

Thanks for updating to OC 0.7,9 !
1. "Rearrange the order of you config.plist to match the new one here" - how do I do that ?
2. Is the updated file you now uploaded now include the touchscreen feature ? or do I still need to follow the method you mentioned in your original guide?
3.Why animations are not so smooth on my system. Is it the same on yours?

**Comment by dikamsiyoung** [comment]
Hi ozalboher,

Have you been able to follow the guide through?

No the one I updated doesn't have touchscreen enabled by default. You'd have to activate that yourself as we don't have the exact same configuration.

Hmmm not sure why animation is slow. I have 4K60Hz active, smooth as butter.

**Comment by ozalboher** [comment]
Thanks for helping ! Appreciate it very much !
